import Head from "next/head"
import Image from "next/image"
import Featured from "../components/Featured"
import Cta from "../components/homepage/Cta"
import Info from "../components/homepage/Info"
import Services from "../components/homepage/Services"
import Speciality from "../components/homepage/Speciality"
import Testimonials from "../components/homepage/Testimonials"

export default function Home() {
  return (
    <div className='w-full h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Featured />
      <Services />
      <Speciality />
      <Info />
      <Cta />
      <Testimonials />
    </div>
  )
}
